Simuler offentlig AFP - førsteutkast
navikt/tjenestepensjon-simulering pull request #86
Opened 2024-01-31 14:54 UTC by antonfofanov

2024-01-31 16:05 UTC, espengjostol requested changes

2024-01-31 16:05 UTC, espengjostol commented on src/main/kotlin/no/nav/tjenestepensjon/simulering/v3/afp/AfpOffentligLivsvarigSimuleringService.kt
> +            AfpOffentligLivsvarigYtelse(it.fraOgMedDato.year, (it.beholdning * 0.0421 * 18.1 / dt.delingstall), it.fraOgMedDato, it.tilOgMedDato)
Mange magiske konstanter her: `70`, `0.0421`, `18.1`.
Disse bør deklareres som konstanter med beskrivende navn.

2024-01-31 16:24 UTC, espengjostol commented on .nais/nais-dev.yaml
> +      value: api://dev-fss.pensjon-q1.pensjon-pen-q1/.default
Vi bør vel bruke **q2** i dev (syntetiske personer)?

2024-02-01 12:14 UTC, espengjostol approved these changes

2024-02-01 12:14 UTC, espengjostol commented on src/main/kotlin/no/nav/tjenestepensjon/simulering/model/domain/pen/AFPOffentligLivsvarigYtelse.kt
> +data class AFPOffentligLivsvarigYtelse(val ar: Int, val belop: Double, val fom: LocalDate, val tom: LocalDate)
Hehe, mitt forslag var motsatt: `AFP` -> `Afp`
(dette er i henhold til [Google Java style guide: Camel case](https://google.github.io/styleguide/javaguide.html#s5.3-camel-case), som jeg synes er en god guide)

2024-02-01 12:21 UTC, espengjostol commented on src/main/kotlin/no/nav/tjenestepensjon/simulering/model/domain/pen/FremtidigInntekt.kt
> +data class FremtidigInntekt(val belop: Int, @JsonProperty("fraOgMed") val fom: LocalDate, @JsonProperty("tilOgMed") val tom: LocalDate)
Dette er bra :)
Da unngår vi at ekstern navngivning påvirker vårt interne domene (og vi kan trygt refaktorere sistnevnte uten at API-et knekker).

2024-02-01 12:21 UTC, antonfofanov commented on src/main/kotlin/no/nav/tjenestepensjon/simulering/model/domain/pen/AFPOffentligLivsvarigYtelse.kt
> +data class AFPOffentligLivsvarigYtelse(val ar: Int, val belop: Double, val fom: LocalDate, val tom: LocalDate)
Ja, jeg ville snakke med deg om dette. Vi har AFP (AFPPrivat og AFPOffentlig) i andre steder i appen som er vrient til å endre, fordi det involverer XML og brukes av eksterne tjenester. Vi kan ikke få bruke CamelCase Afp gjennom hele appen og jeg foreslår å bruke AFP for å være konsekvent.
Vil du fortsatt ha Afp med CamelCase?

2024-02-01 12:26 UTC, antonfofanov commented on src/main/kotlin/no/nav/tjenestepensjon/simulering/model/domain/pen/AfpOffentligLivsvarigYtelse.kt
> +data class AfpOffentligLivsvarigYtelse(val ar: Int, val belop: Double, val fraOgMedDato: LocalDate, val tilOgMedDato: LocalDate)
Det er litt problematisk å bytte `ar` og `maned` at disse ble brukt konsekvent rundt omkring i appen. Det ville være ikke konsekvent å bruke `aar`, `maaned` og `beloep`, mens i alle andre steder er det `ar`, `maned` og `belop`.

2024-02-01 12:28 UTC, espengjostol commented on src/main/kotlin/no/nav/tjenestepensjon/simulering/model/domain/pen/AFPOffentligLivsvarigYtelse.kt
> +data class AFPOffentligLivsvarigYtelse(val ar: Int, val belop: Double, val fom: LocalDate, val tom: LocalDate)
Det aller viktigste synes jeg er at det er konsekvent, så vi beholder `AFP` nå.
Men det er et dårlig arkitekturmessig tegn at eksterne entiteter dikterer navngivning i vårt domene.
Her ser det ut til å være behov for et [anti-corruption layer](https://martinfowler.com/articles/refactoring-external-service.html).
Men det kan være en oppgave til senere.

2024-02-01 12:42 UTC, espengjostol commented on src/main/kotlin/no/nav/tjenestepensjon/simulering/model/domain/pen/AfpOffentligLivsvarigYtelse.kt
> +data class AfpOffentligLivsvarigYtelse(val ar: Int, val belop: Double, val fraOgMedDato: LocalDate, val tilOgMedDato: LocalDate)
Ok, vi lar det være. Ser ut til at det anti-corruption-layeret er ganske aktuelt å innføre :)

2024-02-01 12:42 UTC, antonfofanov commented on src/main/kotlin/no/nav/tjenestepensjon/simulering/rest/SimuleringAfpEndpoint.kt
> +        private val LOG = LoggerFactory.getLogger(AfpOffentligLivsvarigSimuleringService::class.java)
Jeg tenker at det er et flott forslag, men KotlinLogging brukes ikke i appen fra før. Da ville jeg foreslå det i et annet pull-request, fordi å bytte til kotlinlogging overalt ville slå på alle områder i appen enn bare det nye endepunktet

2024-02-01 13:45 UTC, antonfofanov commented on src/main/kotlin/no/nav/tjenestepensjon/simulering/config/WebClientConfig.kt
> +    ): WebClient = WebClient.builder()
Appen startet fint med bruk av webclientbuilder, men det stoppet testene til å initialisere på tross av ekstra konfigurasjon av webclientbuilder i test. Jeg lar den stå som det er per nå. Med mindre du vet om en løsning?

2024-02-01 14:25 UTC, espengjostol commented on src/main/kotlin/no/nav/tjenestepensjon/simulering/config/WebClientConfig.kt
> +    ): WebClient = WebClient.builder()
Merkelige greier, med `webClientBuilder` så feiler `WebClientConfigTest` første gang, men "re-run failed test" går ok. Virker som noe oppstarts-timing-greier.

Dette virker fint i pensjonskalkulator-backend, f.eks. [PdlPersonClientTest](https://github.com/navikt/pensjonskalkulator-backend/blob/main/src/test/kotlin/no/nav/pensjon/kalkulator/person/client/pdl/PdlPersonClientTest.kt#L34)

2024-02-01 15:09 UTC, espengjostol commented on src/main/kotlin/no/nav/tjenestepensjon/simulering/config/WebClientConfig.kt
> +                    .header(HttpHeaders.AUTHORIZATION, adClient.getToken(scope)) //TODO cache token
Apropos caching av token, så ser det ut til at [MSAL](https://learn.microsoft.com/en-us/entra/identity-platform/msal-acquire-cache-tokens#acquiring-tokens-silently-from-the-cache) gjør det for oss.

2024-02-02 10:12 UTC, antonfofanov commented on src/main/kotlin/no/nav/tjenestepensjon/simulering/config/WebClientConfig.kt
> +    ): WebClient = WebClient.builder()
Det kan være det, men jeg tenker at det er litt fint å injecte en ferdig konfigurert WebClient. Jeg har lagt til en testconfig for builderen, og testene kjører grønt nå.

2024-02-02 10:14 UTC, merged

2024-02-02 11:06 UTC, espengjostol commented on src/main/kotlin/no/nav/tjenestepensjon/simulering/config/WebClientConfig.kt
> +    ): WebClient = WebClient.builder()
Jo, ser poenget.
På den annen side: Ved å injecte en ferdig konfigurert `WebClient.Builder` (minus `baseUrl`), så unngår man kodeduplisering. Nå er det duplisert kode mellom `afpBeholdningWebClient` og `penWebClient`.

2024-02-02 11:13 UTC, antonfofanov commented on src/main/kotlin/no/nav/tjenestepensjon/simulering/config/WebClientConfig.kt
> +    ): WebClient = WebClient.builder()
Ja, koden blir duplisert, ser den. Men det er greit å duplisere teknisk kode. Gevinsten å følge DRY til punkt og prikke er minimal i dette tilfelle

2024-02-02 11:35 UTC, espengjostol commented on src/main/kotlin/no/nav/tjenestepensjon/simulering/config/WebClientConfig.kt
> +    ): WebClient = WebClient.builder()
Forresten så bør vi vel legge til en `Nav-Call-Id`-header i webClient-kallene, for å kunne trace kallene.